### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by LSantos06** [pedroyan/MimAjudaBE#10]
Implementar no UserService os seguintes métodos:
- [X] xmlUser getUser(id) - *GET*;
- [X] User createUser(xmlUser) -  *PUT*;
- [X] User updateUser(xmlUser) - *POST*;
- [X] id deleteUser(id) - *DELETE*.

Após implementar tais métodos, implementar os services restantes:
- [x] Avaliação; 
- [X] Matéria;
- [X] OfertarMatéria;
- [X] Pedido;
- [X] Tag.

**Comment by pedroyan** [comment]
Em relação ao update, não se esqueça de validar se o usuário existe. Caso o selectById retornar null, certifique-se de retornar um HTTP status code de erro junto com uma mensagem de erro. Faça isso para cada caso de erro que você conseguir pensar.
Possíveis casos:

1. Não encontrou o usuário
2. Erro durante o update no Banco

**Comment by pedroyan** [comment]
Para saber mais sobre HTTP status code e retorno de informação leia: 
http://stackoverflow.com/questions/4687271/jax-rs-how-to-return-json-and-http-status-code-together
